
server:
  port: 8081

spring:

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  batch:
    job:
      enabled: false
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: never
#  main:
#    web-application-type: none

  jackson:
    serialization:
      fail-on-empty-beans: false

  session:
    store-type: redis

  redis:
    cache:
      host: 15.164.99.241  # localhost 15.164.99.241
      port: 6379
    session:
      host: 15.164.99.241  # localhost 15.164.99.241
      port: 6380

  kafka:
    topic:
      name: seonggonDo
    topic-json:
      name: seonggonDo_json

    consumer:
      bootstrap-servers: localhost:9092
      group-id: foo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'

    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cwhetp4kpcdx.ap-northeast-2.rds.amazonaws.com:3306/ward_study
    username: mooh2jj
    password: doseong9114!!

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ward_study?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: doseong9114!!

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ehtjd33@gmail.com
    password: zmgoccjzlfqowudj
    properties:
      mail:
        smtp:
          starttls:
            enable: true

logging:
  level:
    org.hibernate.SQL: debug
